# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0002_auto_20161202_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='found',
            field=models.NullBooleanField(verbose_name=b'Found'),
        ),
    ]
