# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0003_auto_20161203_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.BigIntegerField(default=None),
        ),
    ]
