# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0004_auto_20161205_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='found',
            field=models.NullBooleanField(default=None, verbose_name=b'Found'),
        ),
    ]
