# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0005_auto_20161205_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
