# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0006_auto_20161208_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qr_code',
            field=models.CharField(default=None, max_length=800, null=True),
        ),
    ]
