# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0007_auto_20161208_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qr_code',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
