# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostnfound', '0008_auto_20161218_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
